services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/foodsbd
    depends_on:
      - mongodb
    restart: always
  frontend:
    build: ./frontend
    ports:
      - 8081:80
    restart: always
  mongodb:
   image: mongo
   volumes:
    - dbdata:/data/db
   restart: always
volumes:
  dbdata: