name: Build Docker images from project
on: #[workflow_dispatch]
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build -t lukas2207/beimage:latest ./backend
        docker build -t lukas2207/frimage:latest ./frontend
    - name: push images to dockerhub
      run: |
        docker login -u lukas2207 -p ${{ secrets.DOCKERHUBTOKEN }}
        docker push lukas2207/beimage:latest
        docker push lukas2207/frimage:latest
    
