name: Build Docker images fro project
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
      docker build -t lukas2207/beimage:latest ./backend
      run: |
      docker build -t lukas2207/frimage:latest ./frontend
    
